/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droi_hellojni_JniUtil */

#ifndef _Included_com_droi_hellojni_JniUtil
#define _Included_com_droi_hellojni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droi_hellojni_JniUtil
 * Method:    openDevice
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jint JNICALL Java_com_droi_hellojni_JniUtil_openDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_droi_hellojni_JniUtil
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_droi_hellojni_JniUtil_closeDevice
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif

